sudo: required
language: python
python: "3.7"

install:
  - pip install pipenv coverage pytest-coverage python-coveralls flake8
  - pipenv install
 
script:
# TODO FLAKE8 lots of errors. Need to be fixed, but later
#  - flake8 src
  - export PYTHONPATH=$(pwd)/src; pytest --verbose src --cov src

after_success:
  - coveralls
