sudo: required
language: python
python: "3.7"

env:
    # TODO add more arango versions when they exist
    # TODO could split tests so non-arango tests aren't run for every version
    - ARANGODB_VER=arangodb3-linux-3.5.0

install:
  - wget https://download.arangodb.com/arangodb35/Community/Linux/$ARANGODB_VER.tar.gz
  - tar xfz $ARANGODB_VER.tar.gz
  - export ARANGO=`pwd`/$ARANGODB_VER/bin

  - pip install pipenv coverage pytest-cov python-coveralls flake8
  - pipenv install
 
script:
# TODO FLAKE8 lots of errors. Need to be fixed, but later
#  - flake8 src
  - mkdir arangodata
  - $ARANGO start --starter.mode single --starter.data-dir ./arangodata
  - export PYTHONPATH=$(pwd):$(pwd)/src; pytest --verbose --cov=. .
  - $ARANGO stop

after_success:
  - coveralls
