version: '3'

# Clustered arangodb build


services:

  arangodb:
    image: arangodb
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
    volumes:
      - ./arangodb-data:/data
